src/books/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.BooksListView.as_view(), name='list'),
    url(r'^list$', views.BooksListView.as_view(), name='list'),
    url(r'^search$', views.BooksSearchView.as_view(), name='search'),
    url(r'^toggle/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.book_toggle_view, name='toggle'),
    url(r'^edit/(?P<pk>[0-9,a-z,A-Z]+)/$', views.EditBook.as_view(), name='edit'),
    url(r'^delete/(?P<pk>[0-9,a-z,A-Z]+)/$', views.DeleteBook.as_view(), name='delete'),
    url(r'^create$', views.CreateBook.as_view(success_url='list'), name='create'),
    url(r'^view/(?P<pk>[0-9,a-z,A-Z]+)/$', views.ViewBook.as_view(), name='details'),
    url(r'^upvote/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.vote_book, {'value': 1}, name='upvote'),
    url(r'^downvote/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.vote_book, {'value': -1}, name='downvote'),
    url(r'^block_comment/(?P<pk>[0-9,a-z,A-Z]+)/$', views.CommentBlock.as_view(), name='comment_block'),
    url(r'^unblock_comment/(?P<pk>[0-9,a-z,A-Z]+)/$', views.comment_unblock, name='comment_unblock'),
    url(r'^isbn_fetch$', views.isbn_info, name='isbn_fetch'),
    url(r'^tag/add/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.AddTag.as_view(), name='add_tag'),
    url(r'^purchase/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.purchase_request, name='purchase'),
    url(r'^take_return/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.take_return_book, name='take_return'),

    url(r'^file/add/(?P<isbn>[0-9]+)/$', views.AddBookFile.as_view(), name='add_file'),
    url(r'^file/edit/(?P<pk>[0-9]+)/$', views.EditBookFile.as_view(), name='edit_file'),
    url(r'^file/delete/(?P<pk>[0-9]+)/$', views.DeleteBookFile.as_view(), name='delete_file'),
]

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),

    url(r'^readlist/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.readlist_add_remove, name='readlist_toggle'),
]

src/stroustrup/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import books.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^books/', include(books.urls, namespace='books')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^', include(accounts.urls, namespace='accounts')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/profiles/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
import uuid
import random
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models import Sum, Count
from django.db.models.functions import Coalesce

from books.models import Book, ReadersListRecord


class BaseProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                primary_key=True)
    slug = models.UUIDField(default=uuid.uuid4, blank=True, editable=False)

    read_books = models.ManyToManyField(Book, blank=True, related_name='readers')

    picture = models.ImageField('Profile picture',
                                upload_to='profile_pics/%Y-%m-%d/',
                                null=True,
                                blank=True)
    bio = models.CharField('Short Bio', max_length=200, blank=True, null=True)
    email_verified = models.BooleanField('Email verified', default=False)

    def get_absolute_url(self):
        return reverse('profiles:show', args=[self.slug])

    def get_taken_books(self):
        result = self.user.readerslistrecord_set.filter(date_returned=None)
        return result

    def get_recommended_books(self):
        read_books_ids = self.read_books.values_list('pk', flat=True)
        unread_books = Book.objects.filter(hidden=False) \
                           .annotate(rating=Coalesce(Sum('vote__action'), 0)) \
                           .exclude(pk__in=read_books_ids)

        top_rated_all = unread_books.order_by('-rating')

        top_genres = self.read_books.values('genre') \
                         .annotate(c=Count('genre')).order_by('-c')[:5]
        top_genres_list = [obj['genre'] for obj in top_genres]
        top_rated_by_genre = unread_books.filter(genre__in=top_genres_list) \
                                         .order_by('-rating')
        # TODO: Add queryset with top books by tags of read books
        result = list((top_rated_all | top_rated_by_genre).distinct()[:25])
        random.shuffle(result)
        return result

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Profile(BaseProfile):

    def __str__(self):
        return "{}'s profile". format(self.user)

src/profiles/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.contrib.auth import get_user_model
from pagedown.widgets import PagedownWidget
from . import models

User = get_user_model()


class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('name'),
        )

    class Meta:
        model = User
        fields = ['name']


class ProfileForm(forms.ModelForm):
    bio = forms.CharField(widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('picture'),
            Field('bio'),
            Submit('update', 'Update', css_class="btn-success"),
        )

    class Meta:
        model = models.Profile
        fields = ['picture', 'bio']

src/profiles/views.py
from __future__ import unicode_literals
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from books.models import Book
from django.http import HttpResponse
from . import forms
from . import models


class ShowProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/show_profile.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        if slug:
            profile = get_object_or_404(models.Profile, slug=slug)
            user = profile.user
        else:
            user = self.request.user

        if user == self.request.user:
            kwargs["editable"] = True
        kwargs["show_user"] = user
        return super(ShowProfile, self).get(request, *args, **kwargs)


class EditProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/edit_profile.html"
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if "user_form" not in kwargs:
            kwargs["user_form"] = forms.UserForm(instance=user)
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = forms.ProfileForm(instance=user.profile)
        return super(EditProfile, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user_form = forms.UserForm(request.POST, instance=user)
        profile_form = forms.ProfileForm(request.POST,
                                         request.FILES,
                                         instance=user.profile)
        if not (user_form.is_valid() and profile_form.is_valid()):
            messages.error(request, "There was a problem with the form. "
                           "Please check the details.")
            user_form = forms.UserForm(instance=user)
            profile_form = forms.ProfileForm(instance=user.profile)
            return super(EditProfile, self).get(request,
                                                user_form=user_form,
                                                profile_form=profile_form)
        # Both forms are fine. Time to save!
        user_form.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        messages.success(request, "Profile details saved!")
        return redirect("profiles:show_self")


@login_required
def readlist_add_remove(request, isbn):
    user = request.user
    book = get_object_or_404(Book, isbn=isbn)
    if book in user.profile.read_books.all():
        user.profile.read_books.remove(book)
        return HttpResponse('Removed {} from readlist'.format(book))
    else:
        user.profile.read_books.add(book)
        return HttpResponse('Added {} to readlist'.format(book))

src/profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Profile{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div class="container">
  <h1 class="text-primary">Edit Profile</h1>
  <hr>
  <div class="row">
    <!-- left column -->
    <div class="col-md-3">
      <div class="text-center">
        <img title="profile picture" class="img-circle img-responsive" src="{% thumbnail user.profile.picture|default:'default_profile.png' 140x140 crop %}">
      </div>
    </div>
      
    <!-- edit form column -->
    <div class="col-md-9">
      <h3>Personal info</h3>
      <form enctype="multipart/form-data" method="post">
	{% crispy user_form %}
	{% crispy profile_form %}
      </form>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <a class="btn btn-default pull-right" href="{% url 'accounts:password-change' %}">Change Password</a>
      <a class="btn btn-default pull-right" href="{% url 'accounts:settings' %}">Social Auth Settings</a>
    </div>
  </div>
</div>
{% endblock %}

src/profiles/templates/profiles/show_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load markdown_deux_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Profile{% endblock %}

{% block container %}

<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
      <h1>{{ show_user.get_full_name }}</h1>
      {% if editable %}
      <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">Edit Profile</a>
      {% endif %}
    </div>
    <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'default_profile.png' 140x140 crop %}">
    </div>
  </div>
</div>

<div class="container profile-body">
  <div class="row">
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item text-muted">Profile</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Email:</strong></span> {{ show_user.email|default:"missing" }}
	  {% if show_user.profile.email_verified %}
	    <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="This email address has been verified"></span>
	    <span class="sr-only">Verified</span>
	  {% else %}
	    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true" title="This email address is not verified"></span>
	    <span class="sr-only">Not Verified</span>
	  {% endif %}
	</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span> {{ show_user.date_joined }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Last seen</strong></span> {{ show_user.last_login }}</li>
      </ul>
    </div>
    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class="panel-heading">{{ show_user.get_full_name }}'s Profile
	  {% if show_user.profile.slug %}
	    <a href="{% url 'profiles:show' show_user.profile.slug %}">
	    	<span class="glyphicon glyphicon-link" aria-hidden="true" title="Profile permalink"></span>
	    	<span class="sr-only">Permalink</span></a>
	  {% endif %}
	</div>
        <div class="panel-body">
      	  <strong>Bio</strong>: {{ show_user.profile.bio|markdown }}
      	</div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Read books</div>
        <div class="panel-body">
          <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th>Title</th>
                <th>Authors</th>
                <th>Genre, Tags</th>
                <th>Rating</th>
              </tr>
            </thead>
            <tbody>
              {% for book in show_user.profile.read_books.all %}
              <tr>
                <td>{{ book.title }}</td>
                <td>{{ book.authors_names }}</td>
                <td>{{ book.genre }};
                    {% for tag in book.tags.all %}
                      {{ tag }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                  </td>
                <td>{{ book.get_rating }}</td>
                {# Actions for user #}
                {% if user == show_user %}
                <td>
                  <a href="{% url 'profiles:readlist_toggle' book.isbn %}" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove"></span></a>
                </td>
                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
          </div>
        </div>
      </div>
      
      {% if show_user == user %}
      <div class="panel panel-default">
        <div class="panel-heading">Taken books</div>
        <div class="panel-body">
          <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th>Title</th>
                <th>Authors</th>
                <th>Genre, Tags</th>
                <th>Rating</th>
              </tr>
            </thead>
            <tbody>
              {% for record in show_user.profile.get_taken_books %}
              <tr>
                <td>{{ record.book.title }}</td>
                <td>{{ record.book.authors_names }}</td>
                <td>{{ record.book.genre }};
                    {% for tag in record.book.tags.all %}
                      {{ tag }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                  </td>
                <td>{{ record.book.get_rating }}</td>
                {# Actions for user #}
                {% if user == show_user %}
                <td>
                  <a href="{% url 'books:take_return' record.book.isbn %}" class="btn btn-xs btn-info">Return</a>
                </td>
                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Recommended books</div>
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Authors</th>
                  <th>Genre, Tags</th>
                  <th>Rating</th>
                </tr>
              </thead>
              <tbody>
                {% for book in show_user.profile.get_recommended_books %}
                <tr>
                  <td>{{ book.title }}</td>
                  <td>{{ book.authors_names }}</td>
                  <td>{{ book.genre }};
                    {% for tag in book.tags.all %}
                      {{ tag }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                  </td>

                  <td>{{ book.rating }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            </div>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}