src/books/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.BooksListView.as_view(), name='list'),
    url(r'^list$', views.BooksListView.as_view(), name='list'),
    url(r'^search$', views.BooksSearchView.as_view(), name='search'),
    url(r'^toggle/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.book_toggle_view, name='toggle'),
    url(r'^edit/(?P<pk>[0-9,a-z,A-Z]+)/$', views.EditBook.as_view(), name='edit'),
    url(r'^delete/(?P<pk>[0-9,a-z,A-Z]+)/$', views.DeleteBook.as_view(), name='delete'),
    url(r'^create$', views.CreateBook.as_view(success_url='list'), name='create'),
    url(r'^view/(?P<pk>[0-9,a-z,A-Z]+)/$', views.ViewBook.as_view(), name='details'),
    url(r'^upvote/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.vote_book, {'value': 1}, name='upvote'),
    url(r'^downvote/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.vote_book, {'value': -1}, name='downvote'),
    url(r'^block_comment/(?P<pk>[0-9,a-z,A-Z]+)/$', views.CommentBlock.as_view(), name='comment_block'),
    url(r'^unblock_comment/(?P<pk>[0-9,a-z,A-Z]+)/$', views.comment_unblock, name='comment_unblock'),
    url(r'^isbn_fetch$', views.isbn_info, name='isbn_fetch'),
    url(r'^tag/add/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.AddTag.as_view(), name='add_tag'),
    url(r'^purchase/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.purchase_request, name='purchase'),
    url(r'^take_return/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.take_return_book, name='take_return'),

    url(r'^file/add/(?P<isbn>[0-9]+)/$', views.AddBookFile.as_view(), name='add_file'),
    url(r'^file/edit/(?P<pk>[0-9]+)/$', views.EditBookFile.as_view(), name='edit_file'),
    url(r'^file/delete/(?P<pk>[0-9]+)/$', views.DeleteBookFile.as_view(), name='delete_file'),
]

src/stroustrup/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import books.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^books/', include(books.urls, namespace='books')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^', include(accounts.urls, namespace='accounts')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/books/forms.py
from django import forms
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from crispy_forms.helper import FormHelper
from .models import Book, BookFile, BookComment, Tag
from pagedown.widgets import PagedownWidget, AdminPagedownWidget


class BookForm(forms.ModelForm):
    description = forms.CharField(widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('isbn'),
            Button('fetch', 'Fetch info'),
            Field('title'),
            Field('pages'),
            Field('publish_date'),
            Field('publisher'),
            Field('language'),
            Field('authors'),
            Field('genre'),
            Field('tags'),
            Field('description'),
            Field('picture'),
            Submit('save', 'Save', css_class="btn-success"),
        )

    class Meta:
        model = Book
        fields = ['isbn', 'title', 'pages', 'publish_date', 'tags', 'description',
                  'publisher', 'language', 'authors', 'genre', 'picture']


class BookSearchForm(forms.Form):
    title = forms.CharField(required=False)
    tags = forms.CharField(required=False)
    genre = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super(BookSearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'get'
        self.helper.layout = Layout(
            Field('title'),
            Field('tags'),
            Field('genre'),
            Submit('', 'Search', css_class="btn-success"),
        )


class BookAdminForm(BookForm):
    description = forms.CharField(widget=AdminPagedownWidget())

    class Meta:
        model = Book
        fields = ['isbn', 'title', 'pages', 'publish_date', 'tags', 'description',
                  'publisher', 'language', 'authors', 'genre', 'picture', 'hidden', 'copies_num']


class BookFileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BookFileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('name'),
            Field('description'),
            Field('file'),
            Submit('save', 'Save', css_class="btn-success"),
        )

    class Meta:
        model = BookFile
        fields = ['name', 'description', 'file']


class BookCommentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BookCommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_method = 'post'
        self.helper.form_class = "form-group"
        self.helper.form_show_labels = False
        self.helper.error_text_inline = True
        self.helper.layout = Layout(
            Field('body', rows="4", css_class='form-control'),
            Submit('send', 'Send', css_class="btn-success"),
        )

    class Meta:
        model = BookComment
        fields = ['body']


class CommentBlockForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CommentBlockForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "form-group"
        self.helper.error_text_inline = True
        self.helper.layout = Layout(
            Field('blocked_reason', rows="4", css_class='form-control'),
            Submit('save', 'Save', css_class="btn-success"),
        )

    class Meta:
        model = BookComment
        fields = ['blocked_reason']


class TagForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TagForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('name'),
            Submit('save', 'Save', css_class="btn-success"),
        )

    class Meta:
        model = Tag
        fields = ['name']

src/books/views.py
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.views import generic
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from django.template.loader import get_template
from django.core.mail import EmailMessage
from . import forms
from .models import Book, Vote, BookFile, Tag, Genre, UP, DOWN, BookComment, ReadersListRecord
import isbnlib

isbnlib.config.add_apikey('isbndb', settings.ISBNDB_API_KEY)


class StaffOnlyView(object):

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super(StaffOnlyView, self).dispatch(request, *args, **kwargs)


class BooksListView(generic.ListView):
    model = Book
    template_name = 'books/list.html'
    context_object_name = 'books'
    paginate_by = 10

    def dispatch(self, request, *args, **kwargs):
        count = request.GET.get('count') or request.COOKIES.get('page_count') or self.paginate_by
        if count != self.paginate_by:
            self.paginate_by = count
            self.new_count = count
        else:
            self.new_count = None
        return super(BooksListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(BooksListView, self).get_context_data(**kwargs)
        page_neighbors_count = 3
        index = context['page_obj'].number - 1
        max_index = len(context['paginator'].page_range)
        start_index = index - page_neighbors_count + 1 if index >= page_neighbors_count + 1 else 0
        end_index = index + page_neighbors_count if index <= max_index - page_neighbors_count else max_index
        page_range = context['paginator'].page_range[start_index:end_index]
        context.update({'page_range': page_range})
        return context

    def render_to_response(self, context, **response_kwargs):
        response = super(BooksListView, self).render_to_response(context, **response_kwargs)
        if self.new_count:
            response.set_cookie('page_count', self.new_count)
        return response


class BooksSearchView(BooksListView, generic.edit.FormView):
    template_name = 'books/search.html'
    form_class = forms.BookSearchForm

    def get_context_data(self, **kwargs):
        context = {'form': self.get_form(self.form_class)}
        return super(BooksSearchView, self).get_context_data(**context)

    def get_queryset(self):
        title = self.request.GET.get('title', '')
        tags = [x for x in self.request.GET.get('tags', '').split(',') if x]
        genre = self.request.GET.get('genre', '')
        object_list = self.model.objects.filter(hidden=False)
        if title:
            object_list = object_list.filter(title__icontains=title) | \
                object_list.filter(isbn__icontains=title)
        if genre:
            object_list = object_list.filter(
                genre__in=Genre.objects.filter(name__icontains=genre))
        if tags:
            object_list = object_list.filter(
                tags__in=Tag.objects.filter(name__in=tags))
        return object_list


class ViewBook(generic.DetailView, generic.edit.FormView):
    model = Book
    form_class = forms.BookCommentForm
    template_name = 'books/details.html'

    def get_context_data(self, **kwargs):
        context = {'form': self.get_form(self.form_class)}
        return super(ViewBook, self).get_context_data(**context)

    def form_valid(self, form):
        book = self.get_object()
        msg = form.cleaned_data['body']
        user = self.request.user
        comment_obj = BookComment(user=user, book=book, body=msg)
        comment_obj.save()
        return redirect('books:details', pk=book.pk)


class EditBook(StaffOnlyView, generic.edit.UpdateView):
    template_name = 'books/edit.html'
    model = Book
    form_class = forms.BookForm


class CreateBook(StaffOnlyView, generic.CreateView):
    template_name = 'books/create.html'
    model = Book
    form_class = forms.BookForm


class DeleteBook(StaffOnlyView, generic.edit.DeleteView):
    model = Book
    success_url = reverse_lazy('books:list')

    def delete(self, request, *args, **kwargs):
        book = self.get_object()
        for obj in book.files.all():
            try:
                obj.file.delete()
            except Exception:
                pass
        return super(DeleteBookFile, self).delete(request, *args, **kwargs)


@user_passes_test(lambda u: u.is_staff)
def book_toggle_view(request, isbn):
    book = get_object_or_404(Book, isbn=isbn)
    book.hidden = not book.hidden
    book.save()
    messages.success(request, "Book '{}' has been {}".format(str(book), 'hidden' if book.hidden else 'shown'))
    return redirect('books:list')


@login_required
def vote_book(request, isbn, value=UP):
    book = get_object_or_404(Book, isbn=isbn)
    if value not in [DOWN, UP]:
        return HttpResponse('Your vote is invalid')
    vote = Vote.objects.filter(book=book, user=request.user).first()
    if vote:
        if vote.action == value:
            vote.delete()
            return HttpResponse('Your vote has been deleted')
    else:
        vote = Vote(book=book, user=request.user)
    vote.action = value
    vote.save()
    return HttpResponse('Your {}vote has been scored'.format('up' if value == UP else 'down'))


class DeleteBookFile(StaffOnlyView, generic.edit.DeleteView):
    model = BookFile
    template_name = 'files/files_confirm_delete.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('books:details', kwargs={'pk': self.book_pk})

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        self.book_pk = obj.book.pk
        try:
            obj.file.delete()
        except Exception:
            pass
        return super(DeleteBookFile, self).delete(request, *args, **kwargs)


class EditBookFile(StaffOnlyView, generic.edit.UpdateView):
    template_name = 'files/edit.html'
    model = BookFile
    form_class = forms.BookFileForm


class AddBookFile(StaffOnlyView, generic.CreateView):
    template_name = 'files/edit.html'
    model = BookFile
    form_class = forms.BookFileForm


class CommentBlock(StaffOnlyView, generic.edit.UpdateView):
    model = BookComment
    form_class = forms.CommentBlockForm
    template_name = 'books/block_comment.html'

    def get_context_data(self, **kwargs):
        context = {'form': self.get_form(self.form_class)}
        return super(CommentBlock, self).get_context_data(**context)

    def form_valid(self, form):
        comment = self.get_object()
        book = comment.book
        comment.blocked = True
        comment.blocked_reason = form.cleaned_data['blocked_reason']
        comment.save()
        messages.success(self.request, "Comment has been blocked")
        return redirect('books:details', pk=book.pk)


@user_passes_test(lambda u: u.is_staff)
def comment_unblock(request, pk):
    comment = get_object_or_404(BookComment, pk=pk)
    comment.blocked = False
    comment.blocked_reason = None
    comment.save()
    messages.success(request, "Comment has been unblocked")
    return redirect('books:details', pk=comment.book.pk)


def isbn_info(request):
    isbn = request.GET.get('isbn', '')
    data = {}
    if isbnlib.notisbn(isbn):
        return JsonResponse(data, status=400)
    description = isbnlib.desc(isbn)
    if description:
        data.update({'description': description})
    try:
        metadata = isbnlib.meta(isbn, 'isbndb')
    except Exception:
        metadata = {}
    data.update({'meta': metadata})
    return JsonResponse(data)


class AddTag(LoginRequiredMixin, generic.FormView):
    template_name = 'tags/add.html'
    model = Tag
    form_class = forms.TagForm

    def get_context_data(self, **kwargs):
        context = {'form': self.get_form(self.form_class),
                   'book': self.book}
        return super(AddTag, self).get_context_data(**context)

    def dispatch(self, request, *args, **kwargs):
        print(kwargs.get('isbn'))
        self.book = get_object_or_404(Book, isbn=kwargs.get('isbn'))
        return super(AddTag, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        name = form.cleaned_data['name']
        tag = Tag.objects.get_or_create(name=name)[0]
        self.book.tags.add(tag)
        return super(AddTag, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('books:details', kwargs={'pk': self.book.pk})


@login_required
def purchase_request(request, isbn):
    template_name = 'books/emails/purchase.html'
    subject = 'Purchase request'
    from_email = request.user.email
    to_email = [settings.ADMIN_EMAIL]
    book = get_object_or_404(Book, isbn=isbn)
    context = {'request': request, 'book': book}
    message = get_template(template_name).render(context)
    msg = EmailMessage(subject, message, to=to_email, from_email=from_email)
    msg.content_subtype = 'html'
    msg.send()
    return redirect('books:details', pk=book.pk)


@login_required
def take_return_book(request, isbn):
    user = request.user
    book = get_object_or_404(Book, isbn=isbn)
    records = ReadersListRecord.objects.filter(book=book, user=user, date_returned=None)
    if records:
        if book.return_book(user):
            messages.success(request, "Book '{}' has been returned".format(str(book)))
        else:
            messages.error(request, "Book '{}' has not been returned".format(str(book)))
    else:
        if book.take_book(user):
            messages.success(request, "Book '{}' has been taken".format(str(book)))
        else:
            messages.error(request, "Book '{}' has not been taken".format(str(book)))

src/books/templates/books/details.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load markdown_deux_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}{{ book.title }} :: Profile{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="books" %}
{% endblock %}


{% block container %}

<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
      <h1>{{ book.title }}</h1>
      {% if book in user.profile.read_books.all %}
      <a href="{% url 'profiles:readlist_toggle' book.isbn %}" class="btn btn-info">Remove from readlist</a>
      {% else %}
      <a href="{% url 'profiles:readlist_toggle' book.isbn %}" class="btn btn-info">Add to readlist</a>
      {% endif %}
      {# Dirtiest hack #}
      {% for record in user.profile.get_taken_books.all %}{% if record.book == book %}
      <a href="{% url 'books:take_return' book.isbn %}" class="btn btn-info">Return</a>
      {% else %}
      <a href="{% url 'books:take_return' book.isbn %}" class="btn btn-info {% if book.copies_num <= 0 %}disabled{% endif %}">Take</a>
      {% endif %}{% empty %}<a href="{% url 'books:take_return' book.isbn %}" class="btn btn-info {% if book.copies_num <= 0 %}disabled{% endif %}">Take</a>{% endfor %}
      <a href="{% url 'books:purchase' book.isbn %}" class="btn btn-success">
        Request purchase
      </a>
      {% if user.is_staff %}
      <a href="{% url 'books:toggle' book.isbn %}" class="btn btn-warning">
      	{% if book.hidden %}Show{% else %}Hide{% endif %}
      </a>
      <a href="{% url 'books:delete' book.isbn %}" class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
    <div class="col-sm-2"><img title="book picture" class="img-responsive" src="{% thumbnail book.picture|default:'default_profile.png' 140x140 crop %}">
    </div>
  </div>
</div>

<div class="container profile-body">
  <div class="row">
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item text-right text-muted"><span class="pull-left">Information</span><a href="{% url 'books:edit' book.isbn %}" class="btn btn-xs btn-info">Edit</a>
        </li>

        <li class="list-group-item text-right"><span class="pull-left"><strong>ISBN</strong></span> {{ book.isbn }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Authors</strong></span> {{ book.authors_names }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Pages</strong></span> {{ book.pages }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Publish date</strong></span> {{ book.publish_date }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Publisher</strong></span> {{ book.publisher }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Language</strong></span> {{ book.language }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Genre</strong></span> {{ book.genre }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Copies left</strong></span> {{ book.copies_num }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Tags</strong></span>
        {% for tag in book.tags.all %}
          {{ tag }}{% if not forloop.last %}, {% endif %}
        {% empty %}
          None
        {% endfor %}
        <a href="{% url 'books:add_tag' book.isbn %}"><span class="glyphicon glyphicon-plus"></span></a>
        </li>
        
        <li class="list-group-item text-right"><span class="pull-left"><strong>Rating</strong></span>
         {{ book.get_rating }} (+{{ book.get_upvotes_count }} / -{{ book.get_downvotes_count }})
        <a href="{% url 'books:upvote' book.isbn%}">
        	<span class="glyphicon glyphicon-thumbs-up" aria-hidden="true" title="Upvote"></span></a>
        <a href="{% url 'books:upvote' book.isbn%}">
        	<span class="glyphicon glyphicon-thumbs-down" aria-hidden="true" title="Downvote"></span></a>
        </li>
        
      </ul>
    </div>
    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class="panel-heading">Description</div>
        <div class="panel-body">
          {{ book.description|default:'No description'|markdown }}
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Readers</div>
        <div class="panel-body">
          {% for profile in book.readers.all %}
          <a href="{{ profile.get_absolute_url }}">{{ profile.user.name }}</a>{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Taken by</div>
        <div class="panel-body">
          {% for record in book.get_current_readers_records.all %}
          <a href="{{ record.user.profile.get_absolute_url }}">{{ record.user.profile.user.name }}</a>{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Files
        <a href="{% url 'books:add_file' book.isbn %}"><span class="pull-right btn btn-xs btn-default">Add file</span></a></div>
	        <div class="panel-body">
          {% if book.files.all %}
	        <div class="table-responsive">
					<table class="table">
						<thead>
							<tr>
								<th>Name</th>
								<th>Description</th>
								<th>File</th>
								{# Header for actions #}
								{% if user.is_staff %}
								<th>Actions</th>
								{% endif %}
							</tr>
						</thead>
						<tbody>
							{% for file in book.files.all %}
							<tr>
								<td>{{ file.name }}</td>
								<td>{{ file.description }}</td>
								<td><span class="glyphicon glyphicon-download-alt"></span> <a href="{{ file.file.url }}">{{ file.filename }}</a></td>
								{# Actions for staff #}
								<td>
									<a href="{% url 'books:edit_file' file.pk %}" class="btn btn-xs btn-info">Edit</a>
									<a href="{% url 'books:delete_file' file.pk %}" class="btn btn-xs btn-danger">Delete</a>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
	        </div>
          {% else %}
          <p>No files for this book.</p>
          {% endif %}

	        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Comments</div>
        <div class="panel-body">
          <form enctype="multipart/form-data" method="post">
          {% crispy form %}
          </form>
          <br>
          {% for comment in book.comments.all %}
          <div class="well">
            <a href="{{ comment.user.profile.get_absolute_url }}">{{ comment.user.name }}</a> on {{ comment.timestamp | date }} {{ comment.timestamp | time }}:
            {% if comment.blocked %}
              <p>Comment has been blocked by moderator</p>
              {% if comment.user == user %}
              <p>Reason: {{ comment.blocked_reason }}</p>
              {% endif %}
            {% else %}
            <p>{{ comment.body }}</p>
            {% endif %}

            {% if user.is_staff %}
              {% if comment.blocked %}
              <a href="{% url 'books:comment_unblock' comment.pk %}" class="btn btn-danger">Unblock</a>
              {% else %}
              <a href="{% url 'books:comment_block' comment.pk %}" class="btn btn-danger">Block</a>
              {% endif %}
            {% endif %}
          </div>
          
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

src/books/templates/books/list.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}{{ block.super }}Books list{% endblock %}

{% block navbar-left %}
	{% include "_navbar.html" with active_link="books" %}
{% endblock %}

{% block container %}
<div class="container text-page">
	<div class="page-header"><h1>Books</h1>
	{% if user.is_staff %}
		<a href="{% url 'books:create' %}"><span class="badge">Create</span></a>
	{% endif %}
	</div>
	<div class="row">
		<div class="list-group">
		{% for book in books %}
			<div class="list-group-item">
				<h2><a href="{% url 'books:details' book.isbn %}">{{ book.title }}</a></h2>
				<p>Authors: {% for author in book.authors.all %}{{ author.full_name }}{% endfor %}</p>
				<p>Publish_date: {{ book.publish_date }}</p>
				<p>Genre: {{ book.genre }}</p>
				{% if book.tags.all %}
				<p>Tags: {% for tag in book.tags.all %}{{ tag }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
				{% endif %}

				{% if user.is_staff %}
				<a href="{% url 'books:edit' book.isbn %}"><span class="badge">Edit</span></a>
				<a href="{% url 'books:toggle' book.isbn %}"><span class="badge alert-warning">
					{% if book.hidden %}Show{% else %}Hide{% endif %}
				</span></a>
				<a href="{% url 'books:delete' book.isbn %}"><span class="badge alert-danger">Delete</span></a>
				{% endif %}

			</div>
		{% empty %}
				No books found.
		</div>
		{% endfor %}
		</div>
	</div>

	{% if is_paginated %}
		<div class="row">
		<ul class="pagination">
			{% if page_obj.has_previous %}
				<li><a href="?page={{ page_obj.previous_page_number }}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span></a></li>
				{% if not 1 in page_range %}
					<li><a href="?page=1">1</a></li>
				{% endif %}
			{% else %}
				<li class="disabled"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span></li>
			{% endif %}
			{% for i in page_range %}
				{% if page_obj.number == i %}
					<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
				{% else %}
					<li><a href="?page={{ i }}">{{ i }}</a></li>
				{% endif %}
			{% endfor %}
			{% if page_obj.has_next %}
				{% if not page_obj.paginator.num_pages in page_range %}
					<li><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
				{% endif %}
				<li><a href="?page={{ page_obj.next_page_number }}"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a></li>
				
			{% else %}
				<li class="disabled"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></li>
			{% endif %}
		</ul>
		</div>
		<div class="row">
			<div class="btn-group">
				<a href="{% url 'books:list' %}?count=5" class="btn btn-default {% if page_obj|length == 5 %}active{% endif %}">5</a>
				<a href="{% url 'books:list' %}?count=10" class="btn btn-default {% if page_obj|length == 10 %}active{% endif %}">10</a>
				<a href="{% url 'books:list' %}?count=20" class="btn btn-default {% if page_obj|length == 20 %}active{% endif %}">20</a>
			</div>
		</div>
	{% endif %}
</div>


{% endblock %}