src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),

    url(r'^settings/$', views.social_settings, name='settings'),
    url(r'^settings/password/$', views.password, name='password'),
]

src/books/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.BooksListView.as_view(), name='list'),
    url(r'^list$', views.BooksListView.as_view(), name='list'),
    url(r'^search$', views.BooksSearchView.as_view(), name='search'),
    url(r'^toggle/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.book_toggle_view, name='toggle'),
    url(r'^edit/(?P<pk>[0-9,a-z,A-Z]+)/$', views.EditBook.as_view(), name='edit'),
    url(r'^delete/(?P<pk>[0-9,a-z,A-Z]+)/$', views.DeleteBook.as_view(), name='delete'),
    url(r'^create$', views.CreateBook.as_view(success_url='list'), name='create'),
    url(r'^view/(?P<pk>[0-9,a-z,A-Z]+)/$', views.ViewBook.as_view(), name='details'),
    url(r'^upvote/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.vote_book, {'value': 1}, name='upvote'),
    url(r'^downvote/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.vote_book, {'value': -1}, name='downvote'),
    url(r'^block_comment/(?P<pk>[0-9,a-z,A-Z]+)/$', views.CommentBlock.as_view(), name='comment_block'),
    url(r'^unblock_comment/(?P<pk>[0-9,a-z,A-Z]+)/$', views.comment_unblock, name='comment_unblock'),
    url(r'^isbn_fetch$', views.isbn_info, name='isbn_fetch'),
    url(r'^tag/add/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.AddTag.as_view(), name='add_tag'),
    url(r'^purchase/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.purchase_request, name='purchase'),
    url(r'^take_return/(?P<isbn>[0-9,a-z,A-Z]+)/$', views.take_return_book, name='take_return'),

    url(r'^file/add/(?P<isbn>[0-9]+)/$', views.AddBookFile.as_view(), name='add_file'),
    url(r'^file/edit/(?P<pk>[0-9]+)/$', views.EditBookFile.as_view(), name='edit_file'),
    url(r'^file/delete/(?P<pk>[0-9]+)/$', views.DeleteBookFile.as_view(), name='delete_file'),
]

src/stroustrup/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import books.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^books/', include(books.urls, namespace='books')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^', include(accounts.urls, namespace='accounts')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/accounts/models.py
from django.db import models

# Create your models here.

src/accounts/forms.py
from __future__ import unicode_literals
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from authtools import forms as authtoolsforms
from django.contrib.auth import forms as authforms
from django.core.urlresolvers import reverse


class LoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False, initial=False)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields["username"].widget.input_type = "email"  # ugly hack

        self.helper.layout = Layout(
            Field('username', placeholder="Enter Email", autofocus=""),
            Field('password', placeholder="Enter Password"),
            HTML('<a href="{}">Forgot Password?</a>'.format(
                reverse("accounts:password-reset"))),
            Field('remember_me'),
            Submit('sign_in', 'Log in',
                   css_class="btn btn-lg btn-primary btn-block"),
            )


class SignupForm(authtoolsforms.UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields["email"].widget.input_type = "email"  # ugly hack

        self.helper.layout = Layout(
            Field('email', placeholder="Enter Email", autofocus=""),
            Field('name', placeholder="Enter Full Name"),
            Field('password1', placeholder="Enter Password"),
            Field('password2', placeholder="Re-enter Password"),
            Submit('sign_up', 'Sign up', css_class="btn-warning"),
            )


class PasswordChangeForm(authforms.PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('old_password', placeholder="Enter old password",
                  autofocus=""),
            Field('new_password1', placeholder="Enter new password"),
            Field('new_password2', placeholder="Enter new password (again)"),
            Submit('pass_change', 'Change Password', css_class="btn-warning"),
            )


class PasswordResetForm(authtoolsforms.FriendlyPasswordResetForm):

    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('email', placeholder="Enter email",
                  autofocus=""),
            Submit('pass_reset', 'Reset Password', css_class="btn-warning"),
            )


class SetPasswordForm(authforms.SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(SetPasswordForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('new_password1', placeholder="Enter new password",
                  autofocus=""),
            Field('new_password2', placeholder="Enter new password (again)"),
            Submit('pass_change', 'Change Password', css_class="btn-warning"),
            )

src/accounts/views.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib import auth, messages
from authtools import views as authviews
from braces import views as bracesviews
from django.conf import settings
from django.shortcuts import render, redirect
from . import forms

from social_django.models import UserSocialAuth

User = get_user_model()


class LoginView(bracesviews.AnonymousRequiredMixin,
                authviews.LoginView):
    template_name = "accounts/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        redirect = super(LoginView, self).form_valid(form)
        remember_me = form.cleaned_data.get('remember_me')
        if remember_me is True:
            ONE_MONTH = 30 * 24 * 60 * 60
            expiry = getattr(settings, "KEEP_LOGGED_DURATION", ONE_MONTH)
            self.request.session.set_expiry(expiry)
        return redirect


class LogoutView(authviews.LogoutView):
    url = reverse_lazy('home')


class SignUpView(bracesviews.AnonymousRequiredMixin,
                 bracesviews.FormValidMessageMixin,
                 generic.CreateView):
    form_class = forms.SignupForm
    model = User
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('home')
    form_valid_message = "You're signed up!"

    def form_valid(self, form):
        r = super(SignUpView, self).form_valid(form)
        username = form.cleaned_data["email"]
        password = form.cleaned_data["password1"]
        user = auth.authenticate(email=username, password=password)
        auth.login(self.request, user)
        return r


class PasswordChangeView(authviews.PasswordChangeView):
    form_class = forms.PasswordChangeForm
    template_name = 'accounts/password-change.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.save()
        messages.success(self.request,
                         "Your password was changed, "
                         "hence you have been logged out. Please relogin")
        return super(PasswordChangeView, self).form_valid(form)


class PasswordResetView(authviews.PasswordResetView):
    form_class = forms.PasswordResetForm
    template_name = 'accounts/password-reset.html'
    success_url = reverse_lazy('accounts:password-reset-done')
    subject_template_name = 'accounts/emails/password-reset-subject.txt'
    email_template_name = 'accounts/emails/password-reset-email.html'


class PasswordResetDoneView(authviews.PasswordResetDoneView):
    template_name = 'accounts/password-reset-done.html'


class PasswordResetConfirmView(authviews.PasswordResetConfirmAndLoginView):
    template_name = 'accounts/password-reset-confirm.html'
    form_class = forms.SetPasswordForm


@login_required
def social_settings(request):
    user = request.user

    try:
        github_login = user.social_auth.get(provider='github')
    except UserSocialAuth.DoesNotExist:
        github_login = None

    try:
        vk_login = user.social_auth.get(provider='vk-oauth2')
    except UserSocialAuth.DoesNotExist:
        vk_login = None

    can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())

    return render(request, 'accounts/social_settings.html', {
        'github_login': github_login,
        'vk_login': vk_login,
        'can_disconnect': can_disconnect
    })


@login_required
def password(request):
    PasswordForm = forms.SetPasswordForm

    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('accounts:password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'accounts/social_password.html', {'form': form})

src/accounts/templates/accounts/auth_base.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block navbar %}
{% endblock %}

{% block container %}
<div class="container form-box">
  <div class="text-center">
    <h2>{% block form_heading %}{% endblock %}</h2>
  </div>
  {% block form %}
  {% endblock %}
</div>

{% endblock container %}

src/accounts/templates/accounts/login.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Log In{% endblock %}

{% block form_heading %}Please Log In{% endblock %}

{% block form %}
  {% crispy form %}

  <div class="form-message">
    <p>
      Don't have an account? <a href="{% url 'accounts:signup' %}">Sign up</a>.
    </p>
    <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>
    <a href="{% url 'social:begin' 'vk-oauth2' %}">Login with VK</a><br>
  </div>
{% endblock form %}

src/accounts/templates/accounts/password-change.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Change{% endblock %}

{% block form_heading %}Password Change{% endblock %}

{% block form %}
  {% crispy form %}
{% endblock form %}

src/accounts/templates/accounts/password-reset-confirm.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Change{% endblock %}

{% block form_heading %}Password Change{% endblock %}

{% block form %}
  {% crispy form %}
{% endblock form %}

src/accounts/templates/accounts/password-reset-done.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Reset Done{% endblock %}

{% block form_heading %}Password Reset Email Sent{% endblock %}

{% block form %}
<div class="form-message">
  <p>
    Please check your mail. You would have received a password reset mail from us.
  </p>
</div>
{% endblock form %}

src/accounts/templates/accounts/password-reset.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Reset{% endblock %}

{% block form_heading %}Password Reset{% endblock %}

{% block form %}
  {% crispy form %}
{% endblock form %}

src/accounts/templates/accounts/signup.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Sign Up{% endblock %}

{% block form_heading %}Signing Up is Free{% endblock %}

{% block form %}
  {% crispy form %}

  <div class="form-message">
    <p>
      Already signed up? <a href="{% url 'accounts:login' %}">Log in</a>.
    </p>
  </div>
{% endblock form %}

src/accounts/templates/accounts/social_password.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Change Password{% endblock %}

{% block form_heading %}Change Password{% endblock %}

{% block form %}

  <div class="form-message">
    {% if not user.has_usable_password %}
      <p style="color: red">You have not defined a password yet.</p>
    {% endif %}

    {% crispy form %}
  </div>
{% endblock form %}

src/accounts/templates/accounts/social_settings.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Login Settings{% endblock %}

{% block form_heading %}Your connected accounts{% endblock %}

{% block form %}

  <div class="form-message">
    <h3>GitHub</h3>
      {% if github_login %}
        <p>Connected as <a href="https://github.com/{{ github_login.extra_data.login }}/" target="_blank">{{ github_login.extra_data.login }}</a></p>
        {% if can_disconnect %}
          <form method="post" action="{% url 'social:disconnect' 'github' %}">
            {% csrf_token %}
            <button type="submit">Disconnect from GitHub</button>
          </form>
        {% else %}
          <button type="button" disabled>Disconnect from GitHub</button>
          <p style="color: red">You must <a href="{% url 'accounts:password' %}">define a password</a> for your account before disconnecting from Github.</p>
        {% endif %}
      {% else %}
        <a href="{% url 'social:begin' 'github' %}">Connect to GitHub</a>
      {% endif %}

    <h3>VK</h3>
      {% if vk_login %}
        <p>Connected as <a href="https://vk.com/id{{ vk_login.extra_data.id }}" target="_blank">{{ vk_login.extra_data.id }}</a></p>
        {% if can_disconnect %}
          <form method="post" action="{% url 'social:disconnect' 'vk-oauth2' %}">
            {% csrf_token %}
            <button type="submit">Disconnect from VK</button>
          </form>
        {% else %}
          <button type="button" disabled>Disconnect from VK</button>
          <p style="color: red">You must <a href="{% url 'accounts:password' %}">define a password</a> for your account before disconnecting from VK.</p>
        {% endif %}
      {% else %}
        <a href="{% url 'social:begin' 'vk-oauth2' %}">Connect to VK</a>
      {% endif %}

	
  </div>
{% endblock form %}